apiVersion: apps/v1
kind: Deployment
metadata:
    name: atn-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: atn
    template:
        metadata:
            labels: {app: atn}
        spec:
            
            containers: [{name: atn, image: 'mubasherm/allthenews:v4', args: [news, 'http://nf-service:8888', weather, 'http://wf-service:8888', door, 'http://35.228.206.59:31080/'], ports: [{containerPort: 8080}]}, {name: atn-redis, image: redis, ports: [{containerPort: 6379}]}]
# the link for the function , sport, 'https://europe-west1-eadmslabs.cloudfunctions.net/mm-ca-function',